#!/bin/sh
# Get the test suites for Rails gems from ~/project/rails (upstream git repo)
# and place them in ~/fedora-packages/rubygem-foo
#
# Usage:
#  ./get-rails-tests 4.0.0
VERSION=$1
gems=(activesupport activemodel activerecord actionview actionpack actionmailer railties)

cd ~/projects/rails
git pull
git checkout v$VERSION

for gem in "${gems[@]}"
do
  echo "Getting test suite for $gem..."

  UPDATED=`ls ~/fedora-packages/rubygem-$gem/ | grep "$gem-$VERSION-tests.tgz"`

  if [ "$UPDATED" == "$gem-$VERSION-tests.tgz" ]; then
    # Files are already in place
    continue
  fi

  cd ~/projects/rails/$gem
  tar czvf $gem-$VERSION-tests.tgz test/
  cp $gem-$VERSION-tests.tgz ~/fedora-packages/rubygem-$gem/.
done

