#!/usr/bin/bash
# Just shortcut for ppprof.rb profiling
# 
# Usage:
#   ./ruby-profile RUBY_PROGRAM
CPUPROFILE_REALTIME=1 CPUPROFILE=/tmp/.curr_ruby_profile RUBYOPT="-r`gem which perftools | tail -1`" $*
pprof.rb --text /tmp/.curr_ruby_profile
