#!/bin/sh
# Prepare the update of all Rails gems at once. It expects
# the Fedora git repositories of gem packages at
# ~/fedora-packages/rubygem-$gem
#
# Usage:
#   ./update-rails-packages OLD_VERSION NEW_VERSION
OLD=$1
NEW=$2

gems=(activesupport activemodel activerecord actionview actionpack actionmailer railties rails)

for gem in "${gems[@]}"
do
  echo "Updating $gem:"
  cd ~/fedora-packages/rubygem-$gem/

  UPDATED=`cat ./rubygem-$gem.spec | grep "Version: $NEW"`
  if [ "$UPDATED" == "Version: $NEW" ]; then
    echo "Already updated. Skipping."
    continue
  fi

  git pull
  git checkout master
  gem fetch $gem --version $NEW

  sed -i -e "s/git checkout v$OLD/git checkout v$NEW/" rubygem-$gem.spec
  sed -i -e "s/$OLD-tests.tgz/$NEW-tests.tgz/" rubygem-$gem.spec
  sed -i -e "s/Version:.*$OLD/Version: $NEW/g" rubygem-$gem.spec
  sed -i -e "s/Release:.*/Release: 1%{?dist}/g" rubygem-$gem.spec

  CHANGELOG='* '
  CHANGELOG+=`date +'%a %b %d %Y'`
  CHANGELOG+=" Josef Stribny <jstribny@redhat.com> - $NEW-1\n"
  CHANGELOG+="- Update to $gem $NEW"

  sed -i -e "s/%changelog/%changelog\n$CHANGELOG\n/g" rubygem-$gem.spec
done

